- name: Post to slack on failure
      if: failure()
      uses: 8398a7/action-slack@v3.9.1
      with:
        status: ${{ job.status }}
        fields: repo,message,author,action,ref,workflow
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

name: slack-notification

on: [push, pull_request, issues]

jobs:
  slack-notifications:
    runs-on: ubuntu-latest
    name: Sends a message to Slack when a push, a pull request or an issue is made
    steps:
    - name: Check out source code
        uses: actions/checkout@v1
      - name: Post to slack on failure
      uses: 8398a7/action-slack@v3.9.1
      with:
        status: ${{ job.status }}
        fields: repo,message,author,action,ref,workflow
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        
        

