name: change-Environmenet

on: [push, pull_request, issues]

jobs:
  weekday_job:
    runs-on: ubuntu-latest
    env:
      RUNNER_OS: $RUNNER_OS
    steps:
      - name: "Check OS Type"
        if: ${{ env.OS == 'Linux' || env.OS == 'Window' }}
        run: echo "$RUNNER_OS OS! $RUNNER_OS"
        env:
          RUNNER_OS: Window
    
          
      
      
        

