name: change-process-notification

on: [push, pull_request, issues]

jobs:
  weekday_job:
    runs-on: ubuntu-latest
    env:
      DAY_OF_WEEK: Mon
    steps:
      - name: "Hello world when it's Monday"
        if: ${{ env.DAY_OF_WEEK == 'Mon' ||env.DAY_OF_WEEK == 'Sun' }}
        run: echo "Hello $FIRST_NAME $middle_name $Last_Name $DAY_OF_WEEK, today is Monday!"
        env:
          FIRST_NAME: Mona
          middle_name: The
          Last_Name: Octocat
         
      
      
        

