name: change-Environmenet

on: [push, pull_request, issues]

jobs:
  weekday_job:
    runs-on: ubuntu-latest
    env:
      OS: Linux
    steps:
      - name: "Check OS Type"
        if: ${{ env.OS == 'Linux' || env.OS == 'Window' }}
        run: echo "$OS OS!"
        env:
          OS: Window
          
      
      
        

