name: slack-notification

on: [push, pull_request, issues]

jobs:
  slack-notifications:
    runs-on: ubuntu-latest
    name: Sends a message to Slack when a push, a pull request or an issue is made
    steps:
      - name: Notify slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: PankajGovindRao/hello-world-javascript-action@main
        with:
          args: '{\"channel\":\"D023ZJ4R45R\",\"text\":\"Hello world\"}'
        
        

